/**
 * UserRoadmap Mongoose Model
 * 
 * Represents a student's personal, active learning path cloned from a
 * ClusterTemplate or dynamically generated by Gemini AI.
 * 
 * Tracks milestone progression with an automated state machine:
 * - Node 1 starts as 'in_progress'
 * - Nodes 2..N start as 'locked'
 * - Passing a node's comprehension quiz marks it 'completed', awards XP,
 *   and automatically unlocks the next milestone to 'in_progress'.
 */

const mongoose = require('mongoose');
const { resourceSchema, quizQuestionSchema } = require('./schemas/RoadmapNodeSchema');

const userMilestoneSchema = new mongoose.Schema(
  {
    order: {
      type: Number,
      required: true,
      min: 1,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
      trim: true,
    },
    estimatedHours: {
      type: Number,
      required: true,
      min: 1,
      default: 5,
    },
    status: {
      type: String,
      enum: ['locked', 'in_progress', 'completed'],
      default: 'locked',
      index: true,
    },
    completedAt: {
      type: Date,
      default: null,
    },
    quizScore: {
      type: Number,
      default: null,
      min: 0,
      max: 100,
    },
    quizPassed: {
      type: Boolean,
      default: false,
    },
    userNotes: {
      type: String,
      default: '',
      maxLength: 5000,
    },
    resources: {
      type: [resourceSchema],
      default: [],
    },
    quizQuestions: {
      type: [quizQuestionSchema],
      default: [],
    },
  },
  { _id: true }
);

const userRoadmapSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      default: '',
    },
    source: {
      type: String,
      enum: ['cluster_template', 'gemini', 'blueprint'],
      default: 'cluster_template',
    },
    totalEstimatedHours: {
      type: Number,
      default: 0,
    },
    overallProgress: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    status: {
      type: String,
      enum: ['in_progress', 'completed', 'abandoned'],
      default: 'in_progress',
      index: true,
    },
    lastAccessedAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
    nodes: {
      type: [userMilestoneSchema],
      default: [],
      validate: [
        (val) => Array.isArray(val) && val.length > 0,
        'A user roadmap must have at least one milestone node',
      ],
    },
  },
  {
    timestamps: true,
  }
);

/**
 * Helper method to recalculate overall progress percentage
 */
userRoadmapSchema.methods.recalculateProgress = function () {
  if (!this.nodes || this.nodes.length === 0) {
    this.overallProgress = 0;
    return;
  }

  const completedCount = this.nodes.filter((n) => n.status === 'completed').length;
  this.overallProgress = Math.round((completedCount / this.nodes.length) * 100);

  if (this.overallProgress === 100) {
    this.status = 'completed';
  } else if (this.status === 'completed') {
    this.status = 'in_progress';
  }
};

const UserRoadmap = mongoose.model('UserRoadmap', userRoadmapSchema);

module.exports = UserRoadmap;
